/**
 * E2E — BetSlipPhotoImport (Wave N4)
 *
 * 2.A — E2E "stub": mocks OpenRouter via page.route(), sem gastar tokens Gemini.
 *       Roda na suite padrão.
 *
 * Auth strategy: Supabase Admin API `generate_link` (magic-link) → follow redirect
 * → cookies injetados pelo SSR. Requer SUPABASE_SERVICE_ROLE_KEY,
 * NEXT_PUBLIC_SUPABASE_URL e E2E_USER_EMAIL.
 *
 * Skip guard: se qualquer var obrigatória estiver ausente, todos os testes
 * são marcados como skip — nunca fail na CI por falta de configuração.
 *
 * O mock OpenRouter retorna 2 legs:
 *   - Leg 1: Flamengo × Palmeiras — sem fixture no DB (auto-link só possível com DB real)
 *   - Leg 2: Arsenal × Chelsea — idem
 *
 * Na UI de confirmação o componente renderiza as legs parseadas, mesmo sem
 * fixture vinculada — o fluxo termina com "Adicionar N legs ao bilhete".
 *
 * Cleanup: remove legs criadas via DELETE /api/bet-slip/legs (se existir)
 * ou simplesmente navega de volta — legs em draft não afetam outros testes.
 */

import { test, expect, type Page } from "@playwright/test";
import * as path from "path";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";

// ── Env guards ────────────────────────────────────────────────────────────────

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";
const ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "";
const E2E_EMAIL = process.env.E2E_USER_EMAIL ?? "rafael@meteoradigital.io";

const authReady =
  SUPABASE_URL.length > 0 &&
  SERVICE_ROLE_KEY.length > 0 &&
  ANON_KEY.length > 0 &&
  E2E_EMAIL.length > 0;

// ── Auth helper ───────────────────────────────────────────────────────────────

/**
 * Authenticates the E2E user via Supabase Admin magic-link + cookie injection.
 *
 * Strategy:
 *   1. Admin supabase-js client: `generateLink` → get hashed_token
 *   2. Anon supabase-js client: `verifyOtp({ token_hash })` → get session
 *   3. Inject `sb-{project}-auth-token` cookie into the Playwright context
 *
 * This avoids following the Supabase redirect (which points to production URL)
 * and directly establishes the session in the browser context.
 *
 * Cookie format per @supabase/ssr: JSON.stringify([access_token, refresh_token])
 */
async function authenticateViaCookieInjection(page: Page): Promise<boolean> {
  if (!authReady) return false;

  // 1. Generate hashed_token via Admin supabase-js client
  const adminClient = createSupabaseClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: genData, error: genErr } =
    await adminClient.auth.admin.generateLink({
      type: "magiclink",
      email: E2E_EMAIL,
    });

  if (genErr || !genData) {
    console.error("[e2e-auth] generateLink failed:", genErr?.message);
    return false;
  }

  const hashedToken = genData.properties.hashed_token;
  if (!hashedToken) {
    console.error("[e2e-auth] no hashed_token in generateLink response");
    return false;
  }

  // 2. Exchange token for session using anon client
  const anonClient = createSupabaseClient(SUPABASE_URL, ANON_KEY, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
  });

  const { data: verifyData, error: verifyErr } = await anonClient.auth.verifyOtp({
    token_hash: hashedToken,
    type: "magiclink",
  });

  if (verifyErr || !verifyData.session) {
    console.error("[e2e-auth] verifyOtp failed:", verifyErr?.message);
    return false;
  }

  const { access_token, refresh_token } = verifyData.session;

  // 3. Use @supabase/ssr createServerClient to generate the properly-formatted cookies
  //    (format: "base64-<base64_encoded_session_json>") then inject into Playwright context.
  const cookiesToInject: Array<{ name: string; value: string }> = [];
  const ssrClient = createServerClient(SUPABASE_URL, ANON_KEY, {
    cookies: {
      getAll: () => [],
      setAll: (cookies) => {
        for (const c of cookies) {
          cookiesToInject.push({ name: c.name, value: c.value });
        }
      },
    },
  });
  await ssrClient.auth.setSession({ access_token, refresh_token });

  if (cookiesToInject.length === 0) {
    console.error("[e2e-auth] no cookies generated by setSession");
    return false;
  }

  await page.context().addCookies(
    cookiesToInject.map((c) => ({
      name: c.name,
      value: c.value,
      domain: "localhost",
      path: "/",
      httpOnly: false,
      secure: false,
      sameSite: "Lax" as const,
    })),
  );

  return true;
}

// ── Fixtures path ─────────────────────────────────────────────────────────────

const MOCK_BET_SLIP_PNG = path.join(__dirname, "fixtures", "mock-bet-slip.png");

// ── Seed helpers ─────────────────────────────────────────────────────────────

/**
 * Creates (or reuses) a draft bet slip + one seed leg so the FAB becomes visible
 * and the BetSlipDrawer (with "Importar foto") can be opened.
 *
 * If the user already has a draft slip, adds the leg to it (avoids maybeSingle() error).
 * Returns { slipId, legId } for cleanup. legId is the seed leg to remove.
 */
async function seedDraftSlip(
  userId: string,
): Promise<{ slipId: number; legId: number } | null> {
  if (!authReady) return null;
  const adminClient = createSupabaseClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = adminClient as any;

  // 1. Find existing draft slip or create one
  let slipId: number;
  const { data: existing } = await db
    .from("bet_slips")
    .select("id")
    .eq("user_id", userId)
    .eq("status", "draft")
    .limit(1)
    .maybeSingle();

  if (existing) {
    slipId = existing.id;
  } else {
    const { data: newSlip, error: slipErr } = await db
      .from("bet_slips")
      .insert({ user_id: userId, status: "draft", stake_total: null, potential_return: null })
      .select("id")
      .single();
    if (slipErr || !newSlip) {
      console.error("[e2e-seed] bet_slips insert failed:", slipErr?.message);
      return null;
    }
    slipId = newSlip.id;
  }

  // 2. Add a seed leg (we'll remove this in cleanup)
  const { data: leg, error: legErr } = await db
    .from("bet_slip_legs")
    .insert({
      slip_id: slipId,
      home_team: "E2E Seed Home",
      away_team: "E2E Seed Away",
      market: "1X2",
      side: "Casa",
      odd_taken: 1.5,
      fixture_id: null,
      league: null,
      kickoff_utc: null,
    })
    .select("id")
    .single();

  if (legErr || !leg) {
    console.error("[e2e-seed] bet_slip_legs insert failed:", legErr?.message);
    return null;
  }

  return { slipId, legId: leg.id };
}

async function getTestUserId(): Promise<string | null> {
  if (!authReady) return null;
  const adminClient = createSupabaseClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const { data: users } = await adminClient.auth.admin.listUsers();
  const user = users?.users?.find((u) => u.email === E2E_EMAIL);
  return user?.id ?? null;
}

/**
 * Removes only the seed leg (not the whole slip, which may have real data).
 */
async function cleanupSeedLeg(legId: number): Promise<void> {
  if (!authReady) return;
  const adminClient = createSupabaseClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (adminClient as any).from("bet_slip_legs").delete().eq("id", legId);
}

// ── Tests ─────────────────────────────────────────────────────────────────────

test.describe("bet-slip-photo · stub (mocked OpenRouter)", () => {
  // Serial mode: each test needs a fresh Supabase OTP (one-time use per token)
  test.describe.configure({ mode: "serial" });
  test.use({ viewport: { width: 1440, height: 900 } });

  test("fluxo completo: upload → confirmação → commit (stub)", async ({ page }, testInfo) => {
    // Teste de FLUXO (força viewport 1440×900), não de layout mobile. Roda só no
    // desktop-chromium: rodar em paralelo nos 2 projetos colide no mesmo usuário
    // E2E (OTP one-time + seed/cleanup de bilhete compartilhado).
    test.skip(
      testInfo.project.name !== "desktop-chromium",
      "fluxo de upload — só desktop (evita corrida de OTP/seed entre projetos)",
    );
    // OCR é Server Action: o OpenRouter é chamado no servidor. Nos E2E o app
    // aponta OPENROUTER_BASE_URL para o mock (tests/e2e/support/mock-openrouter.mjs),
    // que devolve 2 legs (Flamengo, Arsenal). page.route não serviria aqui.
    test.skip(
      !authReady,
      "Needs SUPABASE_SERVICE_ROLE_KEY + NEXT_PUBLIC_SUPABASE_URL + E2E_USER_EMAIL for magic-link auth",
    );

    // 1. Auth via cookie injection
    const authed = await authenticateViaCookieInjection(page);
    test.skip(!authed, "auth via cookie injection failed — check Supabase Admin API credentials");

    // 2. Seed a draft slip leg so the FAB becomes visible (FAB invisible when 0 legs)
    const userId = await getTestUserId();
    test.skip(!userId, "could not resolve test user ID");
    const seedResult = await seedDraftSlip(userId!);
    test.skip(!seedResult, "could not seed draft slip leg");

    // 3. Navigate to fixtures list (where the FAB appears in the layout)
    await page.goto("/fixtures");
    await expect(page).not.toHaveURL(/login/, { timeout: 10_000 });

    // 4. FAB should be visible (has the seed leg)
    const fab = page.locator("[data-bet-slip-fab]");
    await expect(fab).toBeVisible({ timeout: 10_000 });

    // 5. Click FAB to open the drawer
    await fab.click();

    // 6. Drawer opens — "Importar foto" button appears in header
    const drawer = page.getByRole("dialog", { name: /bilhete múltipla/i });
    await expect(drawer).toBeVisible({ timeout: 5_000 });
    const importBtn = page.getByRole("button", { name: /importar foto/i });
    await expect(importBtn).toBeVisible({ timeout: 5_000 });

    // 7. Upload the mock PNG via the hidden file input
    const fileInput = page.locator('input[type="file"][accept="image/*"]');
    await expect(fileInput).toBeAttached();
    await fileInput.setInputFiles(MOCK_BET_SLIP_PNG);

    // 8. Wait for confirmation dialog (parseBetSlipPhoto usa o mock via OPENROUTER_BASE_URL)
    const confirmDialog = page.getByRole("dialog", { name: /confirmar legs/i });
    await expect(confirmDialog).toBeVisible({ timeout: 15_000 });

    // 9. Both mock legs should be visible. Texto completo da leg evita colidir
    // com as opções de auto-match (`<option>Flamengo × Coritiba…`) no dropdown.
    await expect(page.getByText("Flamengo × Palmeiras")).toBeVisible();
    await expect(page.getByText("Arsenal × Chelsea")).toBeVisible();

    // 10. Add button should be enabled
    const addBtn = page.getByRole("button", { name: /adicionar/i });
    await expect(addBtn).toBeVisible();
    await expect(addBtn).toBeEnabled();

    // 11. Click "Adicionar N legs ao bilhete"
    await addBtn.click();

    // 12. Confirmation dialog closes; return to normal drawer state
    await expect(confirmDialog).not.toBeVisible({ timeout: 10_000 });

    // Cleanup: remove only the seed leg
    await cleanupSeedLeg(seedResult!.legId);
  });
});
